services:
  - type: web
    name: izumi-v2
    env: node
    branch: main
    repo: https://github.com/sataniceypz/Izumi-v2.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_ID
        sync: false
      - key: BOT_INFO
        value: ğ„ğ˜ğğ™ ; ğ—œğ—­ğ—¨ğ— ğ—œ-ğ—«ğ—— ; https://i.imgur.com/Uc0uIkO.jpeg
      - key: PREFIX
        value: ^[.]
      - key: WORK_TYPE
        value: private
      - key: STICKER_PACKNAME
        value: ğ—œğ—­ğ—¨ğ— ğ—œ ğ—«ğ——;ğ„ğ˜ğğ™
      - key: AUDIO_DATA
        value: ğ„ğ˜ğğ™ ; ğ—œğ—­ğ—¨ğ— ğ—œ-ğ—«ğ—— ; https://i.imgur.com/Uc0uIkO.jpeg
      - key: SUDO
        value: false
      - key: ALLWAYS_ONLINE
        value: false
      - key: CAPTIOM
        value: ğ—œğ—­ğ—¨ğ— ğ—œ-ğ—«ğ——
      - key: DATABASE_URL
        sync: false
